<a href="https://colab.research.google.com/github/balipacholi/Machine-Learning/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[4]

np.int64(5)

In [ ]:
a[4] = 13
a

array([ 1,  2,  3,  4, 13,  6])

In [ ]:
a[:3]

array([1, 2, 3])

In [ ]:
b = a[3:]
b

array([ 4, 13,  6])

In [ ]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array_2d[1,2]

np.int64(6)

In [ ]:
array_2d[2,0] = 20
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [20,  8,  9]])

In [ ]:
array_2d[1:]

array([[ 4,  5,  6],
       [20,  8,  9]])

In [ ]:
array_2d[:5]
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [20,  8,  9]])

# Array Attributes

In [ ]:
# The number of dimensions of an array is contained in the ndim attribute
a.ndim

1

In [ ]:
b.ndim

1

In [ ]:
array_2d.ndim

2

In [ ]:
#The shape of an array is a tuple of non-negative intergers that specify the number of elements along each dimension
a.shape

(6,)

In [ ]:
b.shape

(3,)

In [ ]:
array_2d.shape

(3, 3)

In [ ]:
a = np.array(23)
print('No of Dimensions - ', a.ndim) # The number of dimensions of an array is contained in the ndim attribute.
print('Shape -', a.shape) # The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
print('Len of Shape - ', len(a.shape))
print('size -',a.size) # total number of elements in array is contained in the size attribute.
print('datatype -',a.dtype)

No of Dimensions -  0
Shape - ()
Len of Shape -  0
size - 1
datatype - int64


In [ ]:
a = np.array([1.0,2.4])
print('No of Dimensions - ', a.ndim) # The number of dimensions of an array is contained in the ndim attribute.
print('Shape -', a.shape) # The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
print('Len of Shape - ', len(a.shape))
print('size -',a.size) # total number of elements in array is contained in the size attribute.
print('datatype -',a.dtype)

No of Dimensions -  1
Shape - (2,)
Len of Shape -  1
size - 2
datatype - float64


In [ ]:
a = np.array([[1,2],[4,5]])
print('No of Dimensions - ', a.ndim) # The number of dimensions of an array is contained in the ndim attribute.
print('Shape -', a.shape) # The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
print('Len of Shape - ', len(a.shape))
print('size -',a.size) # total number of elements in array is contained in the size attribute.
print('datatype -',a.dtype)

No of Dimensions -  2
Shape - (2, 2)
Len of Shape -  2
size - 4
datatype - int64


In [ ]:
a = np.array([[1,2,5],[2,6,7],[8,9,10]])
print('No of Dimensions - ', a.ndim) # The number of dimensions of an array is contained in the ndim attribute.
print('Shape -', a.shape) # The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
print('Len of Shape - ', len(a.shape))
print('size -',a.size) # total number of elements in array is contained in the size attribute.
print('datatype -',a.dtype)

No of Dimensions -  2
Shape - (3, 3)
Len of Shape -  2
size - 9
datatype - int64


In [ ]:
a = np.array([[11,42,50,4],[2,6,7,82],[8,9,100,2],[7,10,14,90]])
print('No of Dimensions - ', a.ndim) # The number of dimensions of an array is contained in the ndim attribute.
print('Shape -', a.shape) # The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
print('Len of Shape - ', len(a.shape))
print('size -',a.size) # total number of elements in array is contained in the size attribute.
print('datatype -',a.dtype)

No of Dimensions -  2
Shape - (4, 4)
Len of Shape -  2
size - 16
datatype - int64


In [ ]:
a = np.array([[
                [[11,42,50,4],
                 [2,6,7,82]]
                ],
                [
                  [[8,9,100,2],
                  [7,10,14,90]]
                 ],
              [
                  [[2,3,4,5],
                   [6,7,8,9]]
              ]])
print('No of Dimensions - ', a.ndim) # The number of dimensions of an array is contained in the ndim attribute.
print('Shape -', a.shape) # The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
print('Len of Shape - ', len(a.shape))
print('size -',a.size) # total number of elements in array is contained in the size attribute.
print('datatype -',a.dtype)

No of Dimensions -  4
Shape - (3, 1, 2, 4)
Len of Shape -  4
size - 24
datatype - int64


In [ ]:
a = np.array([[
                [[11,42,50,4],
                 [2,6,7,82]],
                 [[1,2,3,4],
                   [5,6,7,8]]
                ],
                [
                  [[8,9,100,2],
                  [7,10,14,90]],
                  [[1,2,3,4],
                   [5,6,7,8]]
                 ],
              [
                  [[2,3,4,5],
                   [6,7,8,9]],
                    [[1,2,3,4],
                   [5,6,7,8]]
              ]])
print('No of Dimensions - ', a.ndim) # The number of dimensions of an array is contained in the ndim attribute.
print('Shape -', a.shape) # The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
print('Len of Shape - ', len(a.shape))
print('size -',a.size) # total number of elements in array is contained in the size attribute.
print('datatype -',a.dtype)

No of Dimensions -  4
Shape - (3, 2, 2, 4)
Len of Shape -  4
size - 48
datatype - int64


# How to create a basic array

This section covers np.zeros(),np.ones(),np.empty(),np.arange(),np.linspace()

In [3]:
#Creating an array filled with 0's
np.zeros(2)

array([0., 0.])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.zeros((2,3,4,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [6]:
#creating an array filled with 1's
np.ones(2)

array([1., 1.])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.ones((1,2,3,7))

array([[[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]]])

In [14]:
# Create an array and you want to override all the array elements later, So right now assign some garbage value to it Hence, create empty array
np.empty(3)

array([0. , 0.5, 1. ])

In [15]:
np.empty((4,3))

array([[6.43454220e-316, 0.00000000e+000, 2.10077583e-312],
       [6.79038654e-313, 2.22809558e-312, 2.14321575e-312],
       [2.35541533e-312, 6.79038654e-313, 2.22809558e-312],
       [2.14321575e-312, 2.46151512e-312, 2.41907520e-312]])

In [18]:
#Create an array with range elements
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [21]:
#create an array with the range of evenly spaced intervals. (first number, last number, step size)
# Where the last number is not inclusive
np.arange(6,30,3)

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [23]:
#Create an array with values that are spaced lineraly in a specified interval (first number, last number, number of elements)
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

# Specifying Your data type

In [25]:
#Default data type is floating point (np.float64), You can explicitly specify which data type you want using the dtype keyword
x = np.ones(2, dtype=np.int64)
x

array([1, 1])