<a href="https://colab.research.google.com/github/balipacholi/Machine-Learning/blob/main/Numpy_tutorial2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

# Sort array

In [ ]:
arr = np.array([2,1,5,3,7,4,6,8])


In [ ]:
# Sort the numbers in ascending order
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# argsort -> Indirect sort along a specified axis
arr = np.array([10,30,20])
np.argsort(arr) # return indexes of the elements before sorting the array and place the index at the elements place after sorting

array([0, 2, 1])

In [ ]:
# lexsort -> Indirect stable sort on mulitple keys
names = np.array(['A', 'B', 'C', 'D'])
age = np.array([21, 20, 21, 20])
marks = np.array([80, 90, 70, 95])

# Sort by age first, then marks i.e, np.lexsort((secondary_key, primary_key))
index = np.lexsort((marks, age))

print(index)
print(names[index])

[1 3 2 0]
['B' 'D' 'C' 'A']


In [ ]:
# searchsorted -> Find elements in a sorted array
arr = np.array([10, 20, 30, 40, 50])

print(np.searchsorted(arr, 25))

2


In [ ]:
# searchsorted -> Find multiple elements in a sorted array, if element is not there then return the index where that value will fall
print(np.searchsorted(arr, [20, 40, 30, 100, 70, 25, 5]))


[1 3 2 5 5 2 0]


In [ ]:
# searchsorted -> Find multiple elements as same in a sorted array
arr = np.array([10, 20, 20, 20, 30])

print(np.searchsorted(arr, 20, side='left'))
print(np.searchsorted(arr, 20, side='right'))

1
4


In [ ]:
# partition -> partial sort
arr = np.array([9, 1, 8, 2, 7, 3, 6, 4, 5])

print(np.partition(arr, 4)) # first 4 elements are sorted

[1 2 3 4 5 6 7 8 9]


In [ ]:
# partition -> partial sort
arr = np.array([9, 1, 8, 2, 7, 3, 6, 4, 5])
k = 3

print('Array elements until that indexed is printed', arr[:k])
print('Array elements until that index is printed in sorted form', np.partition(arr, 3)[:k])

Array elements until that indexed is printed [9 1 8]
Array elements until that index is printed in sorted form [1 2 3]


# Concatenate Array

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# axis means vertical stacking on top of each other
x = np.array([[1,2],[4,5]])
y = np.array([[5,9]])

print('Shape of x :', x.shape)
print('Shape of y:', y.shape)
np.concatenate((x,y), axis=0)

Shape of x : (2, 2)
Shape of y: (1, 2)


array([[1, 2],
       [4, 5],
       [5, 9]])

# Reshaping Arrays

In [ ]:
# Gives a new shape to an array without changing the data
# array you want to reproduce needs to have the same number of elemets as the original array
#(start, stop, step)
a = np.arange(2, 12, 2)
print(a)
print('Shape of a:', a.shape)

NameError: name 'np' is not defined

In [ ]:
# reshape the array to an array with 3 rows and 2 columns
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
arr = np.arange(1,7)
print(arr)

#reshape to 3 rows and 3 columns
arr.reshape(3,2)

[1 2 3 4 5 6]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#reshape to 2 rows and 2 columns
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])