<a href="https://colab.research.google.com/github/balipacholi/Machine-Learning/blob/main/Numpy_tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [3]:
import numpy as np

# Convert a 1D array into a 2D array (how to add a new axis to an array)

In [ ]:
#np.newaxis and np.expand_dims to increase the dimensions of your existing array
#np.newaxis increases the dimensions of your array by one dimension when used once. eg-> 1D to 2D, 2D to 3D and so on.

a = np.array([1,2,3,4,5,6])
a.shape
print("ndim",a.ndim)



ndim 1


In [ ]:
#np.newaxis to add a new axis
row_vector = a[np.newaxis, :] # convert 1D to row vector
print("row_vector :", row_vector)
print ("shape :",row_vector.shape)
print("ndim",row_vector.ndim)

row_vector : [[1 2 3 4 5 6]]
shape : (1, 6)
ndim 2


In [ ]:
col_vector = a[:, np.newaxis]
print("col_vector :", col_vector)
print ("shape :",col_vector.shape)
print("ndim",col_vector.ndim) # To print dimensions

col_vector : [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
shape : (6, 1)
ndim 2


In [ ]:
# use np.expand_dims to add an axis at index postion 1
col = np.expand_dims(a, axis=1) # column vector
print("col :", col)
print ("shape :",col.shape)
print("ndim",col.ndim)

col : [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
shape : (6, 1)
ndim 2


In [ ]:
row = np.expand_dims(a, axis=0) #row vector
print("row :", row)
print ("shape :",row.shape)
print("ndim",row.ndim)

row : [[1 2 3 4 5 6]]
shape : (1, 6)
ndim 2


# Indexing and Slicing

In [ ]:
# index and slice Numpy arrays in the same ways you can slice python lists
data = np.array([1, 2, 3])
print("data[1]",)
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [4]:
arr = np.array([12, 89, 45])
arr[1:] #Print elements from 1st index till last index element(inclusive)

array([89, 45])

In [5]:
arr[2:] #Print elements from 2nd index till last index element(inclusive)

array([45])

In [6]:
arr[2] #Print elements of 2nd index

np.int64(45)

In [7]:
arr[3:] # print elements from 3rd index till last element but, vector don't have 3rd element so it will return an empty

array([], dtype=int64)

In [8]:
arr[-2:] # print last 2 elements

array([89, 45])

In [9]:
arr[-2] # Print last second element of the vector

np.int64(89)

In [11]:
arr[:-2] # Start from beginning
# Go up to the element before the last 2 elements
# So it removes the last two elements

array([12])

In [12]:
arr[:1] # Give all the elements except last 2 elements

array([12])

# Slicing

In [13]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a[a<6]

array([1, 2, 3, 4, 5])

In [14]:
a < 6 #Check for the conditions which match or is true

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [15]:
arr = np.array([[10,98,23,12], [23,45,76,97], [1,54,27,39]])
arr[arr < 50]

array([10, 23, 12, 23, 45,  1, 27, 39])

In [16]:
arr < 50

array([[ True, False,  True,  True],
       [ True,  True, False, False],
       [ True, False,  True,  True]])

In [18]:
arr[(arr>80) | (arr>40)]

array([98, 45, 76, 97, 54])

# np.nonzero() #select elements or indices from an array

In [25]:
a = np.array([[10,98,23,12], [23,45,76,97], [1,54,27,39]])
b = np.nonzero((arr>80) | (arr>40)) # it is printing indices of the element in 2d array like 98 is present a[0(row),1(col)] and 97 -> a[1][3]
print(b)

(array([0, 1, 1, 1, 2]), array([1, 1, 2, 3, 1]))


# Horizontal, vertical Stack Horizontal Split

In [27]:
#Vertical Stack (vstack)
a1 = np.array([[1, 1],
              [2,2]])
a2 = np.array([[3,3],
              [4,4]])
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [28]:
#Horizontal Stack (hstack)
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [37]:
#Split into several smaller arrays using hsplit
#specify the numbers of equally shaped arrays to return or the columns after which the division should occur
x = np.arange(1,25)
print("Original array\n",x)
x = x.reshape(2,12)
print("reshaped array\n", x)
#split this array into 3 equally shaped arrays
print("hsplit - array splitted into 3 equal parts\n")
np.hsplit(x,3)

Original array
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
reshaped array
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
hsplit - array splitted into 3 equal parts



[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

# View & Copies

In [39]:
# Create a new array object that looks at the same data as the original array(shallow copy)
# Numpy functions, as well as operations like indexing and slicing, will return views whenever possible.
# This saves memory and is faster (no cpoy of the data has to be made)
# Important :- Modifying the data in a view also modifies the original array!

arr = np.arange(6)
print("Value of arr\n", arr)
b = arr  #copying of arr to b array
print("Value of b\n", b)
# both arr and b will have same elements in array

# Updating a single element in b
b[4] = 10
print("Value of arr\n", arr) # But, the update will change the elements in the original array as well, Because both are shallow copy (pointing to same memory)
print("Value of b\n", b)

Value of arr
 [0 1 2 3 4 5]
Value of b
 [0 1 2 3 4 5]
Value of arr
 [ 0  1  2  3 10  5]
Value of b
 [ 0  1  2  3 10  5]


In [43]:
# Slicing of array
arr = np.arange(10)
print("Value of arr\n", arr)
b = arr[2:] # B is sliced version of array
print("Value of b\n", b)

# Updating a single element value in b
b[3] = 70
print("Value of arr\n", arr) # It changes 3rd element of b i.e 5 to 70
print("Value of b\n", b)

Value of arr
 [0 1 2 3 4 5 6 7 8 9]
Value of b
 [2 3 4 5 6 7 8 9]
Value of arr
 [ 0  1  2  3  4 70  6  7  8  9]
Value of b
 [ 2  3  4 70  6  7  8  9]


In [48]:
# Deep Copy - Make a complete copy of the array and its data
b2 = arr.copy()
print("Value of arr\n", arr)
print("Value of b2\n", b2)

# Updating b2 some elements
b2[1] = 40
b2[5] = 100
print("Value of arr\n", arr)
print("Value of b2\n", b2) # hence, in deep copy the elements that are changes will not be reflected in the original array as the memory address for both is different.

Value of arr
 [ 0  1  2  3  4 70  6  7  8  9]
Value of b2
 [ 0  1  2  3  4 70  6  7  8  9]
Value of arr
 [ 0  1  2  3  4 70  6  7  8  9]
Value of b2
 [  0  40   2   3   4 100   6   7   8   9]
