<a href="https://colab.research.google.com/github/balipacholi/Machine-Learning/blob/main/Numpy_tutorial4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np

# Basic Array Operations

In [5]:
# Addition Operation -> dimensions of both the arrays should be same as it is element-wise operations
a = np.arange(2, 10)
b = np.arange(5,13)
print(a)
print(b)

print("Addition:\n",a+b)

[2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12]
Addition:
 [ 7  9 11 13 15 17 19 21]


In [6]:
# Subtraction operation
print("Subtraction:\n",b-a)

Subtraction:
 [3 3 3 3 3 3 3 3]


In [7]:
# Multiplication operation
print("Multiplication:\n",a*b)

Multiplication:
 [ 10  18  28  40  54  70  88 108]


In [8]:
# Division operation
print("Division:\n",a/b)

Division:
 [0.4        0.5        0.57142857 0.625      0.66666667 0.7
 0.72727273 0.75      ]


In [9]:
# Printing Sum of the elements in an array
a = np.arange(1, 10)
print(a)

print("Sum of total elements of a:\n",a.sum())

[1 2 3 4 5 6 7 8 9]
Sum of total elements of a:
 45


In [13]:
# To add the rows or the columns in a 2D array
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a.sum(axis=0) // Add all the elements

np.int64(45)

In [19]:
b = a.reshape(3,3)
print(b)
print("addition row wise: \n",b.sum(axis=0))
print("addition column wise: \n",b.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
addition row wise: 
 [12 15 18]
addition column wise: 
 [ 6 15 24]


# Min, Max, Mean, Std, Prod

In [28]:
newArray = np.arange(50,90).reshape(4,10)
print(newArray)
newArray.max()

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]


np.int64(89)

In [29]:
newArray.min()

np.int64(50)

In [30]:
newArray.max(axis = 0)

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [31]:
newArray.min(axis = 1)

array([50, 60, 70, 80])

In [39]:
prodArray = np.array([[1,2,3],[1,2,3]])
print(prodArray.prod()) # get the result of multiplying the elements together

print("column wise multiplication:\n",prodArray.prod(axis = 0))

print("row wise multiplication:\n",prodArray.prod(axis = 1))

36
column wise multiplication:
 [1 4 9]
row wise multiplication:
 [6 6]


In [42]:
# standard_Deviation
std_dev = prodArray.std()
print("Whole 2D element Standard deviation :\n",std_dev)

std_dev_x = prodArray.std(axis = 0)
print("X axis 2D element Standard deviation :\n",std_dev_x)

std_dev_y = prodArray.std(axis = 1)
print("y axis 2D element Standard deviation :\n",std_dev_y)

Whole 2D element Standard deviation :
 0.816496580927726
X axis 2D element Standard deviation :
 [0. 0. 0.]
y axis 2D element Standard deviation :
 [0.81649658 0.81649658]


In [43]:
# Mean
mean_arr = prodArray.mean()
print("Whole 2D element mean :\n",mean_arr)

mean_x = prodArray.mean(axis = 0)
print("X axis 2D element mean :\n",mean_x)

mean_y = prodArray.mean(axis = 1)
print("y axis 2D element mean :\n",mean_y)

Whole 2D element mean :
 2.0
X axis 2D element mean :
 [1. 2. 3.]
y axis 2D element mean :
 [2. 2.]


# Generating random numbers

In [47]:
# Whether you need to randomly initialize weights in an artificial neural network, split data into random sets, or randomly shuffle your dataset
# being able to generate random numbers is essential
# with Generator.integer -> generate random intergers from low(inclusive) to high(exclusive)
# You can set enpoint=True to make the high number inclusive

np.random.randint(2, 9, (3,2)) #( start index, end index, shape of array)

array([[2, 2],
       [6, 7],
       [4, 5]])

In [52]:
# rng stands for random number generator
rng = np.random.default_rng()
rng.integers(10, size=(2,10)) # where 10 is a range and (2,10) is a size

array([[1, 1, 8, 5, 4, 9, 7, 5, 7, 7],
       [7, 8, 3, 9, 7, 8, 3, 3, 5, 2]])

In [53]:
rng.integers(2, 9, (3,2))

array([[3, 5],
       [6, 2],
       [5, 4]])

# Unique Elements

In [54]:
a = np.array([11,11,12,13,14,14,15,16,16,17,17,17,11,20,19,20])
unique_values = np.unique_values(a)
print(unique_values)

[11 12 13 14 15 16 17 19 20]


In [55]:
# Count the occurances of the unique elements
unique_values, occurences_count = np.unique(a, return_counts=True)
print(occurences_count)

[3 1 1 2 1 2 3 1 2]


# Transposing Matrix

In [56]:
# Transpose to reverse or change the axes of an array according to the value you specify
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [58]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [60]:
arr # The original array remains unchanged as transpose of transpose gives you same array

array([[0, 1, 2],
       [3, 4, 5]])

# Flip Array or Reverse Array

In [63]:
arr = np.array([1,2,3,4,5,6,7,8])
arr
reversed_arr = np.flip(arr)
print("Reversed Array :",reversed_arr)

Reversed Array : [8 7 6 5 4 3 2 1]


In [74]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print("original Array: ",arr_2d)

reversed_arr = np.flip(arr_2d)
print("Reversed 2d Array: ",reversed_arr)

arr_2d = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
reversed_arr_axis = np.flip(arr_2d, axis=0)
print("Reversed 2d Array (row): ",reversed_arr_axis)

arr_2d = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
reversed_arr_axis_1 = np.flip(arr_2d, axis=1)
print("Reversed 2d Array (col): ",reversed_arr_axis_1)

print("original Array: ",arr_2d) #original array will not change

original Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reversed 2d Array:  [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Reversed 2d Array (row):  [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Reversed 2d Array (col):  [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
original Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [78]:
# Flip only a row or col
arr_2d = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print("Original Array:\n",arr_2d)

# Reverse the row at index position 1
arr_2d[1] = np.flip(arr_2d[1])
print("Flipped only 1st row of the array:\n", arr_2d)
print("Original Array2:\n",arr_2d)

arr_2d = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print("Original Array:\n",arr_2d)

# Reverse the column at index position 1
arr_2d[:1] = np.flip(arr_2d[1])
print("Flipped only 1st row of the array:\n", arr_2d)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flipped only 1st row of the array:
 [[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
Original Array2:
 [[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flipped only 1st row of the array:
 [[ 8  7  6  5]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Reshaping and Flattening multidimensional arrays

In [81]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("original array: \n",x)

# use Flatten to flatter your array from 2D to 1D array
# It create a new array and hence, do not change the original array
print("Flattened array:")
x.flatten()

original array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array:


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [85]:
# ravel() -> it is also used to flatten array
# The new array created using ravel() is actually a refernce to the parent array(i.e, "view")
# So any changes to the new array will affect the parent array as well. Since, ravel does not create a copy, it is memory efficient
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("original array: \n",x)

# use Flatten to flatter your array from 2D to 1D array
print("Flattened array using ravel:")
a2 = x.ravel()
a2[0] = 100
print(a2)

# Original array content check
print("original array: \n",x)

original array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array using ravel:
[100   2   3   4   5   6   7   8   9  10  11  12]
original array: 
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


# Look For Documentation

In [86]:
help(min)

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.

